### ISSUE TITLE
 INCLUDES values should be wrapped in parentheses

### ISSUE THREAD

**Issue by konradbeck-creditech** [apexfarm/ApexQuery#3]
System.QueryException: expecting a left parentheses, found ':'

INCLUDES (:tmpVar1) instead of INCLUDES :tmpVar1

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_querying_multiselect_picklists.htm

**Comment by inksword** [comment]
Thanks for notifying me the issue. I will fix it by this week.

**Comment by inksword** [comment]
@konradbeck-creditech the bug is fixed now. Sorry for the late reply, I was trying to fix the issue but encounter another one. 

TL;DR;

My test methods for value objects such as when use clauses as keys in Map or Set are breaking. The following guide from Salesforce seems no longer working, so I need to rewrite related test methods. I was thinking it was a small change, but nah. And back to 1 month ago, I was really tired and could not concentrate. Apologies again.

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_collections_maps_keys_userdefined.htm
